name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: elementary/docker:next-unstable

    steps:
      - uses: actions/checkout@v3
